name: EDA
description: Suggest an EDA to be done
title: "[EDA]: "
labels: ["EDA"]
projects: ["johndolan29/5"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone understand what needs to be done
  - type: textarea
    id: description
    attributes:
      label: Describe the analysis to be done
      placeholder: I want to look into X
    validations:
      required: true
