name: EDA
description: Suggest an EDA to be done
labels: ["EDA"]
projects: ["johndolan29/5"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone understand what needs to be done
  - type: textarea
    id: problem
    attributes:
      label: Problem/Question
      placeholder: Need to look into why the model is not performing well on the test set
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Potential Solution/Insights
      placeholder: What are the key questions you want to answer? What data do you need to answer these questions? What are the key insights you hope to gain from this analysis?
    validations:
      required: true
