name: Enhancement
description: Suggest an enhancement feature
title: ""
labels: ["enhancement"]
projects: ["johndolan29/5"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone understand what needs to be done
  - type: textarea
    id: description
    attributes:
      label: Describe the enhancement
      placeholder: Why is this enhancement needed? 
      What problem does it solve?
      Who will benefit from this enhancement?
    validations:
      required: true