name: Enhancement
description: Suggest an enhancement feature
title: "[Enhancement]: "
labels: ["enhancement"]
projects: ["Test project"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone understand what needs to be done
  - type: textarea
    id: description
    attributes:
      label: Describe the enhancement
      placeholder: I want to be able to do X
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "Low"
        - "Medium"
        - "High"
    validations:
      required: true
