name: Create EDA Label

on:
  push:
    branches:
      - '*'  # Listen to all branches'
  workflow_dispatch:

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh label create "$LABELS" --description "Exploratory Data Analysis" --color E99695
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          GH_REPO: ${{ github.repository }}
          LABELS: EDA
