name: Create EDA Label

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-label:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.REPO_TEMPLATE_SECRET }}"

    - name: Create EDA Label
      run: gh api -X POST /repos/${{ github.repository }}/labels -f name='EDA' -f color='00bfff' -f description='Exploratory Data Analysis'
      env:
        GH_TOKEN: ${{ secrets.REPO_TEMPLATE_SECRET }}
