name: Test1

on:
  push:
    branches:
      - 'master'

jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print issue details with priority
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue list --limit 100 --state all \
          --json number,title,projectItems \
          --jq '.[] | {
            number: .number,
            title: .title,
            priority: (
              .projectItems[].fieldValues[] | 
              select(.field.name == "Priority") | 
              .name // "Not specified"
            )
          } | "Issue #\(.number)\nTitle: \(.title)\nPriority: \(.priority)\n---"'
      shell: bash