name: Test1

on:
  push:
    branches:
      - 'master'

jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print issue details with priority
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue list --limit 100 --state all \
          --json number,title,body,labels \
          --jq '.[] | {
            number: .number,
            title: .title,
            priority: (
              (.labels[] | select(.name | test("Priority:.*"; "i")) | .name) //
              (if (.body | test("Priority:.*"; "i"))
               then (.body | match("Priority:.*"; "i").string | sub("Priority:"; "") | sub("^\\s+"; "") | sub("\\s+$"; ""))
               else "Not specified"
               end)
            )
          } | "Issue #\(.number)\nTitle: \(.title)\nPriority: \(.priority)\n---"'
      shell: bash