name: Check Issue Priorities

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Get issues and check priorities
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          GH_REPO: ${{ github.repository }}
        run: |
          # Install required packages
          pip install PyGithub

          # Python script to check issues
          python << EOF
import os
from github import Github

# Authenticate with GitHub
g = Github(os.environ['GITHUB_TOKEN'])

# Get the repository
repo = g.get_repo(os.environ['GITHUB_REPOSITORY'])

# Get all open issues
issues = repo.get_issues(state='open')

print("Issue Priority Report:")
print("=====================")

for issue in issues:
    # Get the priority label
    priority = "Not set"
    for label in issue.labels:
        if label.name.startswith('priority:'):
            priority = label.name.split(':')[1]
            break

    print(f"Issue #{issue.number}: {issue.title}")
    print(f"Priority: {priority}")
    print("---")

print("End of report")
EOF

      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: issue-priority-report
          path: ${{ github.workspace }}/issue_priority_report.txt