name: List Issues

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List all issues
      uses: actions/github-script@v6
      with:
        script: |
          const { data: issues } = await github.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'all'
          });
          
          console.log('All issues in the repository:');
          issues.forEach(issue => {
            console.log(`#${issue.number} - ${issue.title}`);
          });
