name: Test1

on:
  push:
    branches:
      - 'master'

jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print issue details with priority
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching issue details..."
        gh issue list --limit 10 --state all --json number,title,body,labels,assignees,projectItems,projectFields > issues.json
        
        echo "Raw JSON output:"
        cat issues.json
        
        echo -e "\nFormatted output:"
        jq -r '.[] | "Issue #\(.number)\nTitle: \(.title)\nBody: \(.body)\nLabels: \(.labels[].name)\nAssignees: \(.assignees[].login)\nProject Items: \(.projectItems)\nProject Fields: \(.projectFields)\n---"' issues.json
      shell: bash