name: Test1

on:
  push:
    branches:
      - 'master'

jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print issue details
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue list --limit 1000 --state all --json number,title,body \
          --jq '.[] | "Issue #\(.number)\nTitle: \(.title)\nBody:\n\(.body)\n---\n"'
      shell: bash
