name: Test1

on:
  push:
    branches:
      - 'master'

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          GH_REPO: ${{ github.repository }}
