name: Print Issue Titles

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  print-issue-titles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Print issue titles
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        import os
        from github import Github

        # Authenticate using the GitHub token
        g = Github(os.environ['GITHUB_TOKEN'])

        # Get the current repository
        repo = g.get_repo(os.environ['GITHUB_REPOSITORY'])

        # Get all issues and print their titles
        for issue in repo.get_issues(state='all'):
            print(f"Issue #{issue.number}: {issue.title}")
      shell: python
